# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/containernetworking/cni"
  version = "v0.7.0-alpha1"

# https://github.com/kubernetes/client-go#compatibility-matrix
# for details.
[[override]]
  name = "k8s.io/client-go"
  branch = "release-8.0"	# For K8s 1.11.x

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.11"

[[constraint]]
  name = "istio.io/istio"
  branch = "master"

[[override]]
  name = "github.com/openshift/api"
  revision = "dca24d1902afee9d2be02425a2d7c9f910063631"
